project:
  type: website

website:
  title: "Jingjing Yu"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - Project.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""

execute:
  freeze: auto




